files:
  - source: '**/*'
    ignore:
      - .*
      - go.mod
      - go.sum
      - '*.go'
      - .*/
      - i18n/
      - '*.css'
      - '*.js'
      - bin/
    translation: /i18n/%locale%/%original_path%/%original_file_name%
