name: Test
on:
  push:
    branches:
      - '**'

  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
  
      - uses: actions/setup-node@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - run: |
          go run ./bin/patch-crowdin
          npx --yes markdownlint-cli --fix '**/*.md'
