name: Test
on:
  push:
    branches:
      - '**'

  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
  
      - uses: actions/setup-node@v1

      - run: npx markdownlint-cli '**/*.md'
