name: Test

on:
  push:
    branches:
      - "**"

  pull_request:

  schedule:
    - cron: "17 5 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 19

      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.1

      - uses: actions/checkout@v3

      - run: |
          go get -u ./...
          go mod tidy
          go test
          npx markdownlint-cli -i 'i18n/' .
          npx cspell --no-progress '**'
